version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/alert-grid-scada-api
hooks:
  AfterInstall:
    - location: scripts/change_permissions.sh
    - location: scripts/npm_install.sh
      timeout: 300
      runas: root
